---
title: "Data Challenge #2"
author: "Abbie Benfield, Carol Milton, Esa Schenck, Nage Ngo"
date: "3/16/2021"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Packages needed to run code
  # Some are not used anymore but left anyways just in case
library(timetk)
library(tidyverse)
library(ggplot2)
library(plotly)
library(lubridate)
library(gghighlight)
```

```{r, include = FALSE}
# Import movement files
fri_movement <- read_csv("park-movement-Fri.csv",
                         col_types = cols(Timestamp = col_datetime(format = "%Y-%m-%d %H:%M:%S\t")))

sat_movement <- read_csv("park-movement-Sat.csv",
                         col_types = cols(Timestamp = col_datetime(format = "%Y-%m-%d %H:%M:%S\t")))

sun_movement <- read_csv("park-movement-Sun.csv",
                         col_types = cols(Timestamp = col_datetime(format = "%Y-%m-%d %H:%M:%S\t")))
```

```{r, include = FALSE}
# Import communication files
fri_comm <- read_csv("comm-data-Fri.csv",
                     col_types = cols(Timestamp = col_datetime(format = "%Y-%m-%d %H:%M:%S\t")))

sat_comm <- read_csv("comm-data-Sat.csv",
                     col_types = cols(Timestamp = col_datetime(format = "%Y-%m-%d %H:%M:%S\t")))

sun_comm <- read_csv("comm-data-Sun.csv",
                     col_types = cols(Timestamp = col_datetime(format = "%Y-%m-%d %H:%M:%S\t")))
```
 
```{r, include = FALSE}
# Add column that specifies day of message and convert "from" column to character type to match "to"
fri_comm$day = "Fri"
sat_comm$day = "Sat"
sun_comm$day = "Sun"
fri_comm$from = as.character(fri_comm$from)
sat_comm$from = as.character(sat_comm$from)
sun_comm$from = as.character(sun_comm$from)
```

```{r}
# Combine all communication files into 1 df
all_comm <- rbind(fri_comm, sat_comm, sun_comm)
```

```{r}
# Show only the IDs associated with the message
comm_only <- all_comm %>% 
  select(from, to)
```

```{r}
# Number of messages from a specific ID to another ID for all messages
all_from_to_count <- all_comm %>% 
  group_by(from, day) %>% 
  count(from,to)

# Interesting though not incredibly helpful
```

```{r}
# Number of messages sent from each ID 
unique_id_freq <- as.data.frame(table(unlist(comm_only))) %>% 
  arrange(desc(Freq))
head(unique_id_freq, 10)

# How the ID 1278894 was found (see more below)
```

```{r}
# Plots number of messages sent at a specific timestamp
all_timestamp_count <- all_comm %>% 
  group_by(Timestamp, day) %>% 
  count(Timestamp)

all_days_count <- ggplot(data = all_timestamp_count, mapping = aes(x = Timestamp, y = n)) + 
  geom_point(col = "darkred") +
  gghighlight(n >= 500 & n <= 2000,
              unhighlighted_params = list(alpha("steelblue", 0.4))) + 
  facet_wrap(~day, scales = "free_x")

all_days_count

# Note similar patterns in high number of messages sent at once, even though the numbers themselves are different)
```

```{r}
# Plots of message count sent by ID 1278894
  # ID 1278894 must be some kind of mass communication number for the park for sharing info w/ guests and guests asking for info (also see chunk below)
from_id_1278894 <- all_comm %>%
  group_by(Timestamp, day) %>% 
  filter(from == "1278894") %>% 
  count(Timestamp)

plotfrom_id_1278894 <- ggplot(from_id_1278894, aes(x = Timestamp, y = n)) +
  geom_point() + 
  facet_wrap(~day, scale = "free_x")

plotfrom_id_1278894

# Notice very similar shape to highlighted data points in all_days_count plot
```

```{r}
# Plots of message count sent to ID 1278894
to_id_1278894 <- all_comm %>% 
  group_by(Timestamp, day) %>% 
  filter(to == "1278894") %>% 
  count(Timestamp)

plotto_id_1278894 <- ggplot(to_id_1278894, aes(x = Timestamp, y = n)) +
  geom_point() + 
  facet_wrap(~day, scale = "free_x")

plotto_id_1278894
# Notice interesting blocks
```

```{r}
# List of IDs sending messages but not receiving 
sending_notreceiving <- all_comm %>%
  filter(!(all_comm$from %in% all_comm$to))
  
# List of IDs receiving messages but not sending
receiving_notsending <- comm_only %>% 
  filter(!(comm_only$to %in% comm_only$from) & comm_only$to != "external")
  # All to external numbers (62,000 external messages)
```

```{r}
# Info about ID 946866
id_946866messages <- sending_notreceiving %>% 
  filter(from == "946866")
head(id_946866messages)
# Notice 1 message on Sat and 5 on Sun and all are external (and didn't receive any themself); also that messages sent around time of suspected time of crime and/or closure at Wet Land area which countains part of Pavillion

id_946866sat_movement <- sat_movement %>% 
  filter(id == 946866)

id_946866sun_movement <- sun_movement %>% 
  filter(id == 946866)

# Suspicious ID Sat movement
p_id_946866sat <- ggplot(data = id_946866sat_movement, aes(x = X, y = Y)) + 
  geom_point()
p_id_946866sat

p_id_946866sat2 <- ggplot(data = id_946866sat_movement, aes(x = X, y = Y)) + 
  geom_point(alpha = .4)
p_id_946866sat2

p_id_946866sat3 <- ggplot(data = id_946866sat_movement, aes(x = X, y = Y)) + 
  geom_point(alpha = .4) + 
  facet_wrap(~hour(Timestamp))
p_id_946866sat3


# Suspicious ID Sun movement
p_id_946866sun <- ggplot(data = id_946866sun_movement, aes(x = X, y = Y)) + 
  geom_point()
p_id_946866sun

p_id_946866sun2 <- ggplot(data = id_946866sun_movement, aes(x = X, y = Y)) + 
  geom_point(alpha = .4)
p_id_946866sun2

p_id_946866sun3 <- ggplot(data = id_946866sun_movement, aes(x = X, y = Y)) + 
  geom_point(alpha = .4) + 
  facet_wrap(~hour(Timestamp))
p_id_946866sun3


# Conclusion: didn't actually go near pavillion entrance
```

```{r}
# Plotting check-in times for Creighton Pavillion
  # Poor quality graphs but notice changes in both axes for all three plots 
repeat_ids_sunpavillion <- sun_movement %>% 
  filter(X == 32, Y == 33, type == "check-in") %>% 
  group_by(id) %>% 
  filter(n() > 2)

fripavilion_checkin <- fri_movement %>% 
  filter(X == 32, Y == 33, type == "check-in") %>% 
  count(Timestamp)

satpavilion_checkin <- sat_movement %>% 
  filter(X == 32, Y == 33, type == "check-in") %>% 
  count(Timestamp)

sunpavilion_checkin <- sun_movement %>% 
  filter(X == 32, Y == 33, type == "check-in") %>% 
  count(Timestamp)



fripavilion_checkinplot <- ggplot(fripavilion_checkin, aes(x = Timestamp, y = n)) +
  geom_point() +
  labs(title = "Fri")

satpavilion_checkinplot <- ggplot(satpavilion_checkin, aes(x = Timestamp, y = n)) +
  geom_point() +
  labs(title = "Sat")

sunpavilion_checkinplot <- ggplot(sunpavilion_checkin, aes(x = Timestamp, y = n)) +
  geom_point() +
  labs(title = "Sun")

all_pavillion_checkinplots <- grid.arrange(fripavilion_checkinplot, satpavilion_checkinplot, sunpavilion_checkinplot)
all_pavillion_checkinplots
```

```{r}
# Pavillion where crime occurs has entrance in Wet Land, so filtered those messages
wetlandcomm <- all_comm %>% 
  filter(location == "Wet Land") %>% 
  group_by(day) %>% 
  count(Timestamp)

wetlandcommplot <- ggplot(wetlandcomm, aes(x = Timestamp, y = n)) +
  geom_point() + 
  facet_wrap(~day, scales = "free_x", nrow = 3) +
  ylim(NA, 50)

wetlandcommplot
# Notice weird cutout around noon on Sunday (not present on any other days or at any other times) (purposefully chopped y-axis to better show the phenomenon)
```


```{r}
# Writes a CSV (not necessary to run now) and then imports revised CSV I had to wrangle in Excel to get ordered groups, adds ordered groups to original df
# write.csv(n_occur_and_group_size, "/Users/Abbie/OneDrive - Smith College/Spring 2021/SDS235/DC2/original_group_data.csv", row.names = FALSE)

group_data <- read.csv("group_data.csv")

# Condenses communication so that one message sent at same timestamp by 1 ID lists all of the to IDs in one row
group_message_filter <- all_comm %>% 
  group_by(Timestamp, from, day) %>% 
  summarize(to = paste(to, collapse = ", ")) %>% 
  mutate(group = "")

group_message_filter$group <- paste(group_message_filter$from, group_message_filter$to, sep = ", ")


# Lists all IDs (both from and to) in one row
group_ids <- group_message_filter %>%
  select(group, day) %>% 
  mutate(Timestamps = "") %>% 
  mutate(days = "")


# Lists number of different messages within total group and the total number of IDs in that group
n_occur_and_group_size <- group_ids %>% 
  group_by(group) %>% 
  summarize(Timestamps = paste(Timestamp, collapse = ", ")) %>%
  group_by(Timestamps) %>% 
  # Number of Timestamps/IDs is the number of commas + 1
  mutate(n_occur = str_count(Timestamps, ",") + 1) %>% 
  group_by(group) %>% 
  mutate(group_size = str_count(group, ",") + 1)

# EXTERNAL NUMBERS BECOME 0 because it can only interpret numbers
n_occur_and_group_size$ordered_groups = group_data$ordered_group

final_group_data <- n_occur_and_group_size %>% 
  group_by(ordered_groups) %>% 
  summarize(Timestamps = paste(Timestamps, collapse = ", ")) %>%
  group_by(Timestamps) %>% 
  # Number of Timestamps/IDs is the number of commas + 1
  mutate(n_occur = str_count(Timestamps, ",") + 1) %>% 
  group_by(ordered_groups) %>% 
  mutate(group_size = str_count(ordered_groups, ",") + 1)

# Groups larger than 2
larger_group_data <- final_group_data %>% 
  filter(group_size > 2)
```

```{r}
# Communications around time and place when.where crime is thought to have occured
comm11to12sun <- sun_comm %>% 
  filter((hour(Timestamp) >= 11 & hour(Timestamp) <= 12) & (location == "Wet Land" | location == "Coaster Alley") )
```


Trying to Create Clusters in Movement Data

```{python}
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import NearestNeighbors
from sklearn.cluster import DBSCAN

moveFri = pd.read_csv("park-movement-Fri.csv")
moveSat = pd.read_csv("park-movement-Sat.csv")
moveSun = pd.read_csv("park-movement-Sun.csv")

commFri = pd.read_csv("comm-data-Fri.csv")
commSat = pd.read_csv("comm-data-Sat.csv")
commSun = pd.read_csv("comm-data-Sun.csv")

# Must combine movement data and then combine communication data

# Estimating DBSCAN epsilon
db = DBSCAN(eps=0.5, min_samples=10).fit(x)

# Trying to find accurate epsilon value
# Code mostly based on https://towardsdatascience.com/how-to-use-dbscan-effectively-ed212c02e62
nearest_neighbors = NearestNeighbors(n_neighbors=11)
neighbors = nearest_neighbors.fit(x)
distances, indices = neighbors.kneighbors(x)
distances = np.sort(distances[:,10], axis=0)
fig = plt.figure(figsize=(5, 5))
plt.plot(distances)
plt.xlabel("Points")
plt.ylabel("Distance")
```
